### ISSUE TITLE
error when editing activation hint in RA

### ISSUE THREAD

**Issue by phavekes** [OpenConext/Stepup-Project#396]
[This issue is imported from pivotal - Originaly created at Jan 3, 2023 by Peter Havekes](https://www.pivotaltracker.com/story/show/184137448)

When editing the activation-hint-text from the RA portal, the new text can\'t be saved, and the log shows an error :

```
Jan  3 15:53:59 test01.ams.surfconext.nl stepup-ra[5853]: {"channel":"app","level":"WARNING","message":"Command \'Identity:SaveVettingTypeHint\' with UUID \'ed7276fe-ed03-4c0d-b31c-c11a55f47017\' could not be executed (RuntimeException: Argument 1 passed to Surfnet\\Stepup\\Identity\\Value\\VettingTypeFactory::fromData() must be of the type array, null given, called in /opt/openconext/OpenConext-middleware-5.0.5/src/Surfnet/Stepup/Identity/Event/SecondFactorMigratedEvent.php on line 162; #0 /opt/openconext/OpenConext-middleware-5.0.5/src/Surfnet/Stepup/Identity/Event/SecondFactorMigratedEvent.php(162): Surfnet\\Stepup\\Identity\\Value\\VettingTypeFactory::fromData(NULL)\n#1 /opt/openconext/OpenConext-middleware-5.0.5/vendor/broadway/broadway/src/Broadway/Serializer/SimpleInterfaceSerializer.php(50): Surfnet\\Stepup\\Identity\\Event\\SecondFactorMigratedEvent::deserialize(Array)\n#2 /opt/openconext/OpenConext-middleware-5.0.5/vendor/broadway/event-store-dbal/src/DBALEventStore.php(253): Broadway\\Serializer\\SimpleInterfaceSerializer->deserialize(Array)\n#3 /opt/openconext/OpenConext-middleware-5.0.5/vendor/broadway/event-store-dbal/src/DBALEventStore.php(115): Broadway\\EventStore\\Dbal\\DBALEventStore->deserializeEvent(Array)\n#4 /opt/openconext/OpenConext-middleware-5.0.5/src/Surfnet/StepupMiddleware/CommandHandlingBundle/SensitiveData/EventStore/SensitiveDataEventStoreDecorator.php(60): Broadway\\EventStore\\Dbal\\DBALEventStore->load(Object(Surfnet\\Stepup\\Identity\\Value\\IdentityId))\n#5 /opt/openconext/OpenConext-middleware-5.0.5/vendor/broadway/broadway/src/Broadway/EventSourcing/EventSourcingRepository.php(62): Surfnet\\StepupMiddleware\\CommandHandlingBundle\\SensitiveData\\EventStore\\SensitiveDataEventStoreDecorator->load(Object(Surfnet\\Stepup\\Identity\\Value\\IdentityId))\n#6 /opt/openconext/OpenConext-middleware-5.0.5/src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/RegistrationAuthorityCommandHandler.php(130): Broadway\\EventSourcing\\EventSourcingRepository->load(Object(Surfnet\\Stepup\\Identity\\Value\\IdentityId))\n#7 /opt/openconext/OpenConext-middleware-5.0.5/vendor/broadway/broadway/src/Broadway/CommandHandling/SimpleCommandHandler.php(39): Surfnet\\StepupMiddleware\\CommandHandlingBundle\\Identity\\CommandHandler\\RegistrationAuthorityCommandHandler->handleSaveVettingTypeHintCommand(Object(Surfnet\\StepupMiddleware\\CommandHandlingBundle\\Identity\\Command\\SaveVettingTypeHintCommand))\n#8 /opt/openconext/OpenConext-middleware-5.0.5/vendor/broadway/broadway/src/Broadway/CommandHandling/SimpleCommandBus.php(46): Broadway\\CommandHandling\\SimpleCommandHandler->handle(Object(Surfnet\\StepupMiddleware\\CommandHandlingBundle\\Identity\\Command\\SaveVettingTypeHintCommand))\n#9 /opt/openconext/OpenConext-middleware-5.0.5/src/Surfnet/StepupMiddleware/CommandHandlingBundle/Pipeline/DispatchStage.php(51): Broadway\\CommandHandling\\SimpleCommandBus->dispatch(Object(Surfnet\\StepupMiddleware\\CommandHandlingBundle\\Identity\\Command\\SaveVettingTypeHintCommand))\n#10 /opt/openconext/OpenConext-middleware-5.0.5/src/Surfnet/StepupMiddleware/CommandHandlingBundle/Pipeline/StagedPipeline.php(48): Surfnet\\StepupMiddleware\\CommandHandlingBundle\\Pipeline\\DispatchStage->process(Object(Surfnet\\StepupMiddleware\\CommandHandlingBundle\\Identity\\Command\\SaveVettingTypeHintCommand))\n#11 /opt/openconext/OpenConext-middleware-5.0.5/src/Surfnet/StepupMiddleware/CommandHandlingBundle/Pipeline/TransactionAwarePipeline.php(78): Surfnet\\StepupMiddleware\\CommandHandlingBundle\\Pipeline\\StagedPipeline->process(Object(Surfnet\\StepupMiddleware\\CommandHandlingBundle\\Identity\\Command\\SaveVettingTypeHintCommand))\n#12 /opt/openconext/OpenConext-middleware-5.0.5/src/Surfnet/StepupMiddleware/ApiBundle/Controller/CommandController.php(110): Surfnet\\StepupMiddleware\\CommandHandlingBundle\\Pipeline\\TransactionAwarePipeline->process(Object(Surfnet\\StepupMiddleware\\CommandHandlingBundle\\Identity\\Command\\SaveVettingTypeHintCommand))\n#13 /opt/openconext/OpenConext-middleware-5.0.5/vendor/symfony/http-kernel/HttpKernel.php(158): Surfnet\\StepupMiddleware\\ApiBundle\\Controller\\CommandController->handleAction(Object(Surfnet\\StepupMiddleware\\CommandHandlingBundle\\Identity\\Command\\SaveVettingTypeHintCommand), Object(Surfnet\\StepupMiddleware\\CommandHandlingBundle\\Command\\Metadata), Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 /opt/openconext/OpenConext-middleware-5.0.5/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#15 /opt/openconext/OpenConext-middleware-5.0.5/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#16 /opt/openconext/OpenConext-middleware-5.0.5/public/index.php(24): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#17 {main}; {\"identity_id\":\"4cb3daa0-aa3a-4381-83e2-b96bffcc0e9c\",\"source_institution\":\"surfnet.nl\",\"target_name_id\":\"urn:collab:person:surf.nl:clijs001\",\"identity_institution\":\"surf.nl\",\"second_factor_id\":\"b11c6ca4-7dec-44b2-a613-66ea5b7299bc\",\"new_second_factor_id\":\"66c58639-8999-4d79-b8b4-f808b319997f\",\"second_factor_type\":\"yubikey\",\"preferred_locale\":\"nl_NL\"})","context":[],"extra":{"server":"ra.test.surfconext.nl","application":"registration-authority","request_id":"aad0bb386e0645978b66833778134e3a"}}
```

**Comment by phavekes** [comment]
Unable to reproduce on the RA + MW versions currently installed on test2: RA 5.0.2 + MW 5.0.6.
Tested on my own VM and on test2

@phavekes can you verify this? (Michiel Kodde - Jan 18, 2023)
